import React from "react";

export default function Sandbox() {
  return (
    <div>
      01
      <img
        src={require("../assets/images/illustration-element-01.svg")}
        alt=""
      />
      02
      <img
        src={require("../assets/images/illustration-element-02.svg")}
        alt=""
      />
      03
      <img
        src={require("../assets/images/illustration-element-03.svg")}
        alt=""
      />
      04
      <img
        src={require("../assets/images/illustration-element-04.svg")}
        alt=""
      />
      05
      <img
        src={require("../assets/images/illustration-element-05.svg")}
        alt=""
      />
      06
      <img
        src={require("../assets/images/illustration-element-06.svg")}
        alt=""
      />
      07
      <img
        src={require("../assets/images/illustration-element-07.svg")}
        alt=""
      />
      01
      <img
        src={require("../assets/images/illustration-section-01.svg")}
        alt=""
      />
      02
      <img
        src={require("../assets/images/illustration-section-02.svg")}
        alt=""
      />
      03
      <img
        src={require("../assets/images/illustration-section-03.svg")}
        alt=""
      />
      04
      <img
        src={require("../assets/images/illustration-section-04.svg")}
        alt=""
      />
      05
      <img
        src={require("../assets/images/illustration-section-05.svg")}
        alt=""
      />
      06
      <img
        src={require("../assets/images/illustration-section-06.svg")}
        alt=""
      />
      07
      <img
        src={require("../assets/images/illustration-section-07.svg")}
        alt=""
      />
      08
      <img
        src={require("../assets/images/illustration-section-08.svg")}
        alt=""
      />
    </div>
  );
}
